baseURL = "https://www.masoopy.com/"
defaultContentLanguage = 'en'
theme = "LoveIt"
enableRobotsTXT = true
rssLimit = 10

[languages]
  [languages.en]
    weight = 1
    title = "Masoopy"
    languageCode = "en"
    languageName = "English"

    [[languages.en.menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "Posts"
      url = "/posts/"
      # title will be shown when you hover on this menu link
      title = ""
      weight = 1

    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    
    [[languages.en.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
      weight = 3

    [[languages.en.menu.main]]
      identifier = "cheatsheets"
      pre = ""
      post = ""
      name = "Cheatsheets"
      url = "https://cheatsheets.masoopy.com/"
      # title will be shown when you hover on this menu link
      title = ""
      weight = 4


    [[languages.en.menu.main]]
      identifier = "About"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      # title will be shown when you hover on this menu link
      title = ""
      weight = 5

    [languages.fr]
    weight = 2
    title = "Masoopy"
    languageCode = "fr"
    languageName = "Français"

    [[languages.fr.menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "Articles"
      url = "/posts/"
      # title will be shown when you hover on this menu link
      title = ""
      weight = 1

    [[languages.fr.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Balises"
      url = "/tags/"
      title = ""
      weight = 2
    
    [[languages.fr.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Catégories"
      url = "/categories/"
      title = ""
      weight = 3

    [[languages.fr.menu.main]]
      identifier = "cheatsheets"
      pre = ""
      post = ""
      name = "Cheatsheets"
      url = "https://cheatsheets.masoopy.com/"
      # title will be shown when you hover on this menu link
      title = ""
      weight = 4


    [[languages.fr.menu.main]]
      identifier = "About"
      pre = ""
      post = ""
      name = "A propos"
      url = "/a-propos/"
      # title will be shown when you hover on this menu link
      title = ""
      weight = 5


[author]
  name = "Denis G."

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true


[permalinks]
  posts = "/:title/"

[params]
  version = "0.2.X"
#  images = ["/static/images/logo.png"]

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

[params.social]
  Twitter = "nesousx"
  RSS = true

[params.page]
  rssFullText = true

[params.page.share]
  enable = true
  Twitter = true
  HackerNews = true
  Reddit = true
  Linkedin = true


[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]
