baseURL = "https://www.masoopy.com/"
languageCode = "en-us"
title = "Masoopy"
theme = "LoveIt"
enableRobotsTXT = true
rssLimit = 20
copyright = "2022 Masoopy.com"
rssFullText = true

[author]
	name = "Denis"


[permalinks]
  posts = "/:title/"

[params]
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1

  [[menu.main]]
    identifier = "cheatsheets"
    pre = ""
    post = ""
    name = "Cheatsheets"
    url = "/cheatsheets/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2

  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 3
    
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 4

  [[menu.main]]
    identifier = "About"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
